const char *html_content = 
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <title>Full Throttle Bottle</title>\n"
"  <style>\n"
"    body { font-family: 'Trebuchet MS', sans-serif; margin: 20px; }\n"
"    h1 { color: #0066cc; }\n"
"    button { background-color: #4CAF50; border: none; color: white; padding: 10px 20px; \n"
"             text-align: center; text-decoration: none; display: inline-block; \n"
"             font-size: 16px; margin: 4px 2px; cursor: pointer; }\n"
"    .off { background-color: #f44336; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <h1>Full Throttle Bottle</h1>\n"
"  <p>This is a simple web page served by your ESP8266.</p>\n"
"  <div>\n"
"    <button id=\"heatButton\" onclick=\"toggleHeat()\">HEAT OFF</button>\n"
"  </div>\n"
"  <div id=\"response\" style=\"margin-top: 20px; padding: 10px; background-color: #f0f0f0;\"></div>\n"
"  <script>\n"
"    let heatState = false;\n"
"    \n"
"    function toggleHeat() {\n"
"      const endpoint = heatState ? '/api/heat/off' : '/api/heat/on';\n"
"      document.getElementById('response').innerHTML = 'Sending request...';\n"
"      \n"
"      fetch(endpoint)\n"
"        .then(response => response.text())\n"
"        .then(data => {\n"
"          heatState = !heatState;\n"
"          const button = document.getElementById('heatButton');\n"
"          if (heatState) {\n"
"            button.textContent = 'HEAT ON';\n"
"            button.classList.remove('off');\n"
"          } else {\n"
"            button.textContent = 'HEAT OFF';\n"
"            button.classList.add('off');\n"
"          }\n"
"          document.getElementById('response').innerHTML = data;\n"
"        })\n"
"        .catch(error => {\n"
"          document.getElementById('response').innerHTML = 'Error: ' + error;\n"
"        });\n"
"    }\n"
"    \n"
"    window.onload = function() {\n"
"      fetch('/api/heat/status')\n"
"        .then(response => response.text())\n"
"        .then(data => {\n"
"          try {\n"
"            const jsonData = JSON.parse(data);\n"
"            heatState = jsonData.status === \"on\" || jsonData.on === true;\n"
"          } catch (e) {\n"
"            heatState = data.toLowerCase().includes(\"on\");\n"
"          }\n"
"          const button = document.getElementById('heatButton');\n"
"          if (heatState) {\n"
"            button.textContent = 'HEAT ON';\n"
"            button.classList.remove('off');\n"
"          } else {\n"
"            button.textContent = 'HEAT OFF';\n"
"            button.classList.add('off');\n"
"          }\n"
"        })\n"
"        .catch(error => {\n"
"          console.error(\"Error checking initial state:\", error);\n"
"        });\n"
"    };\n"
"  </script>\n"
"</body>\n"
"</html>\n";